### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by jackdong888** [Shaunwei/RealChar#105]
ubuntu@VM-0-12-ubuntu:~/RealChar$ alembic upgrade head
Traceback (most recent call last):
  File "/usr/bin/alembic", line 11, in <module>
    load_entry_point('alembic==1.1.0.dev0', 'console_scripts', 'alembic')()
  File "/usr/lib/python3/dist-packages/alembic/config.py", line 540, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python3/dist-packages/alembic/config.py", line 534, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python3/dist-packages/alembic/config.py", line 511, in run_cmd
    fn(
  File "/usr/lib/python3/dist-packages/alembic/command.py", line 279, in upgrade
    script.run_env()
  File "/usr/lib/python3/dist-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3/dist-packages/alembic/util/compat.py", line 174, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/RealChar/alembic/env.py", line 1, in <module>
    from realtime_ai_character.models.user import User
ModuleNotFoundError: No module named 'realtime_ai_character'

**Comment by jackdong888** [comment]
solved

**Comment by jackdong888** [comment]
closed
