### ISSUE TITLE
python cli.py run-uvicorn and see errors below [run in python3.8]

### ISSUE THREAD

**Issue by jackdong888** [Shaunwei/RealChar#109]
ubuntu@VM-0-12-ubuntu:~/RealChar$ python cli.py run-uvicorn
Running uvicorn server...
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/RealChar/realtime_ai_character/main.py", line 10, in <module>
    from realtime_ai_character.character_catalog.catalog_manager import CatalogManager
  File "/home/ubuntu/RealChar/realtime_ai_character/character_catalog/catalog_manager.py", line 6, in <module>
    from realtime_ai_character.utils import Singleton, Character
  File "/home/ubuntu/RealChar/realtime_ai_character/utils.py", line 4, in <module>
    from langchain.schema import AIMessage, BaseMessage, HumanMessage, SystemMessage
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/agents/tools.py", line 4, in <module>
    from langchain.callbacks.manager import (
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/callbacks/__init__.py", line 3, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/callbacks/aim_callback.py", line 4, in <module>
    from langchain.callbacks.base import BaseCallbackHandler
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/callbacks/base.py", line 7, in <module>
    from langchain.schema.agent import AgentAction, AgentFinish
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/schema/__init__.py", line 3, in <module>
    from langchain.schema.language_model import BaseLanguageModel
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/schema/language_model.py", line 8, in <module>
    from langchain.schema.output import LLMResult
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/schema/output.py", line 31, in <module>
    class ChatGeneration(Generation):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/schema/output.py", line 40, in ChatGeneration
    def set_text(cls, values: Dict[str, Any]) -> Dict[str, Any]:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0.3/u/root-validator-pre-skip

**Comment by Shaunwei** [comment]
looks like pydantic error. give it a try`pip install --upgrade pydantic`?

**Comment by jackdong888** [comment]
> looks like pydantic error. give it a try`pip install --upgrade pydantic`?

hello still have tihs error. I am using python3.8.   Should I update to python3.9 or above?Thanks

**Comment by pycui** [comment]
Yes would recommend Python 3.10+
