### ISSUE TITLE
The  websocket  link automatically closes, what's the problem

### ISSUE THREAD

**Issue by joseph5227** [Shaunwei/RealChar#176]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:    closing handshake failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
INFO:     connection closed
===========================

I only successfully sent the message once,
The  websocket  link automatically closes, what's the problem

**Comment by pycui** [comment]
There is usually some error message before this to show the actual error. E.g. maybe you forgot to run `alembic upgrade head`
