### ISSUE TITLE
Failed to execute 'start' on 'MediaRecorder'

### ISSUE THREAD

**Issue by zeyadalmothafar** [Shaunwei/RealChar#410]
Everything is running for me and the avatar is responding to my talks but i ma getting the following error for some reason:

Failed to execute 'start' on 'MediaRecorder': The MediaRecorder's state is 'recording'. at startRecording (http://localhost:3000/static/js/bundle.js:4157:27) at recognition.current.onend (http://localhost:3000/static/js/bundle.js:4263:9)

**Comment by pycui** [comment]
Hi - what base commit are you running at? Are you able to reproduce this on the prod site (realchar.ai)? Thanks

**Comment by zeyadalmothafar** [comment]
@pycui Sorry for the late response, I don't get the same error when I use realchar.ai

**Comment by zeyadalmothafar** [comment]
@pycui I used 
uvicorn realtime_ai_character.main:app  
to run the app
