### ISSUE TITLE
The server and client are already working, the character doesn't respond

### ISSUE THREAD

**Issue by yinjie1949** [Shaunwei/RealChar#82]
![image](https://github.com/Shaunwei/RealChar/assets/88878773/c122ae8d-247d-4741-89b4-28c5e35668a2)
The server and client are already working, but the character doesn't respond to me,I checked the openai key there is no problem,it works with other program

**Comment by davidtkeane** [comment]
Did you try on different browsers? Just asking?

**Comment by pycui** [comment]
Also, can you check the log from your Docker container or (if running directly) the server side?

**Comment by yinjie1949** [comment]
> Did you try on different browsers? Just asking?

I tried on safari and chrome don't work

**Comment by yinjie1949** [comment]
> Also, can you check and post the log from your Docker container or (if running directly) the server side?

Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 16.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
This is the log

**Comment by yinjie1949** [comment]
2023-07-17 20:52:32,319 - handle_receive - websocket_routes.py - INFO - Client #634658 selected character: Loki
2023-07-17 20:52:44,967 - _generate_context - openai_llm.py - INFO - Found 1 documents
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-07-17 20:54:00,654 - handle_receive - websocket_routes.py - INFO - Client #715 closed the connection
Client #4993138192 left the chat
INFO:     connection closed
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 2.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 16.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 2039, in create_connection
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 668, in arequest_raw
    result = await session.request(**request_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [Operation timed out]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 51, in __call__
    await self.app(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/starlette/routing.py", line 334, in handle
    await self.app(scope, receive, send)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/starlette/routing.py", line 81, in app
    await func(session)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/fastapi/routing.py", line 283, in app
    await dependant.call(**values)
  File "/Users/wangshu/PycharmProjects/realcharacter/RealChar/realtime_ai_character/websocket_routes.py", line 48, in websocket_endpoint
    await asyncio.gather(main_task)
  File "/Users/wangshu/PycharmProjects/realcharacter/RealChar/realtime_ai_character/websocket_routes.py", line 145, in handle_receive
    response = await llm.achat(
               ^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/RealChar/realtime_ai_character/llm/openai_llm.py", line 42, in achat
    response = await self.chat_open_ai.agenerate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/langchain/chat_models/base.py", line 200, in agenerate
    raise exceptions[0]
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/langchain/chat_models/base.py", line 301, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/langchain/chat_models/openai.py", line 411, in _agenerate
    async for stream_resp in await acompletion_with_retry(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/langchain/chat_models/openai.py", line 95, in acompletion_with_retry
    return await _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/langchain/chat_models/openai.py", line 93, in _completion_with_retry
    return await llm.client.acreate(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 372, in arequest
    result = await self.arequest_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 685, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
ERROR:    closing handshake failed
Traceback (most recent call last):
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/Users/wangshu/PycharmProjects/realcharacter/venv/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
INFO:     connection closed

**Comment by yinjie1949** [comment]
![image](https://github.com/Shaunwei/RealChar/assets/88878773/19e669b4-6318-4574-982b-eacf836334f3)
![image](https://github.com/Shaunwei/RealChar/assets/88878773/669fdc1a-ce6e-41bd-8482-b96b4555b013)
 Please check this is the server log and env file .

**Comment by zhouqiang-cl** [comment]
@yinjie1949 you should hide your api key

**Comment by yinjie1949** [comment]
> @yinjie1949 you should hide your api key

Thanks a lot!

**Comment by chenkang404** [comment]
@yinjie1949 ,
i have the same error,
Have you solved the problem
[https://user-images.githubusercontent.com/88878773/254117436-19e669b4-6318-4574-982b-eacf836334f3.png](url)

**Comment by johndpope** [comment]
if you goto chrome / browser / console - can you see any errors?

**Comment by leyiqq** [comment]
I fix the problem by filling the openai_api_base and openai_proxy in chat_models/openai.py

**Comment by Kevin-free** [comment]
> I fix the problem by filling the openai_api_base and openai_proxy in chat_models/openai.py <img alt="WechatIMG103" width="966" src="https://user-images.githubusercontent.com/57703089/255815597-0341b926-f2be-48d7-b00b-9d0b43359402.png">

where is the file `chat_models/openai.py`?
