### ISSUE TITLE
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

### ISSUE THREAD

**Issue by davidtkeane** [Shaunwei/RealChar#87]
`Hi all..

Win 11, powershell and vs-code.

I created a conda env with python=3.10.11.
Installed requirements.
Added APIs
Started sqlite3 test.db "VACUUM;"
alembic upgrade head
python cli.py run-uvicorn
navigate to http://localhost:8000/ and talked to Elon about a job placement interview at spaceX

Error when running python client/cli.py. The server still worked without this, but wondering how to fix. I am a novice, and most likely I am doing something wrong.

(RealChar) PS C:\Users\david\OneDrive\Projects_Mac\Projects\GPT\RealChar> python client/cli.py     
Traceback (most recent call last):
  File "C:\Users\david\OneDrive\Projects_Mac\Projects\GPT\RealChar\client\cli.py", line 191, in <module>
    asyncio.run(main(url))
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\david\OneDrive\Projects_Mac\Projects\GPT\RealChar\client\cli.py", line 182, in main
    await task
  File "C:\Users\david\OneDrive\Projects_Mac\Projects\GPT\RealChar\client\cli.py", line 158, in start_client
    async with websockets.connect(uri) as websocket:
  File "C:\Users\david\anaconda3\envs\RealChar\lib\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
  File "C:\Users\david\anaconda3\envs\RealChar\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\david\anaconda3\envs\RealChar\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\base_events.py", line 1081, in create_connection
    raise exceptions[0]
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\david\anaconda3\envs\RealChar\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

**Comment by pycui** [comment]
We haven't tested running on Windows directly and it's possible it doesn't work. Can you try Docker? if should work out of the box.

**Comment by davidtkeane** [comment]
The server and models, call and text are working perfect on Windows 11. Powershell 7.3.5. Using Google Chrome. 

Its just the remote computer refused error after running the command for client, is the issue using it directally through VS Code in terminal.

Thanks for all the hard work!
